"""add rest models

Revision ID: 3e9806b0f9b5
Revises: b208493abf4b
Create Date: 2026-04-17 22:22:13.726621

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e9806b0f9b5'
down_revision: str | Sequence[str] | None = 'b208493abf4b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archetypes',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('hit_die', sa.Integer(), nullable=False),
    sa.Column('spell_casting_ability', sa.String(length=3), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("spell_casting_ability in ('INT', 'WIS', 'CHA') or spell_casting_ability is null", name=op.f('ck_archetypes_ck_archetypes_spell_casting_ability')),
    sa.CheckConstraint('hit_die in (4, 6, 8, 10, 12)', name=op.f('ck_archetypes_ck_archetypes_hit_die')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_archetypes')),
    sa.UniqueConstraint('name', name=op.f('uq_archetypes_name'))
    )
    op.create_table('skills',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('stat_code', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("stat_code in ('STR', 'DEX', 'CON', 'INT', 'WIS', 'CHA')", name=op.f('ck_skills_ck_skills_stat_code')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills')),
    sa.UniqueConstraint('name', name=op.f('uq_skills_name'))
    )
    op.create_table('spells',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('school', sa.Text(), nullable=True),
    sa.Column('range', sa.Text(), nullable=True),
    sa.Column('duration_time', sa.Text(), nullable=True),
    sa.Column('casting_time', sa.Text(), nullable=True),
    sa.Column('ritual', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('concentration', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('level between 0 and 9', name=op.f('ck_spells_ck_spells_level')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spells')),
    sa.UniqueConstraint('name', name=op.f('uq_spells_name'))
    )
    op.create_table('abilities',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('archetype_id', sa.Uuid(), nullable=True),
    sa.Column('race_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type in ('feat', 'trait', 'feature', 'racial', 'class')", name=op.f('ck_abilities_ck_abilities_type')),
    sa.ForeignKeyConstraint(['archetype_id'], ['archetypes.id'], name=op.f('fk_abilities_archetype_id_archetypes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], name=op.f('fk_abilities_race_id_races'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_abilities')),
    sa.UniqueConstraint('name', name=op.f('uq_abilities_name'))
    )
    op.create_table('character_abilities',
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('ability_id', sa.Uuid(), nullable=False),
    sa.Column('acquired_at_level', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('acquired_at_level is null or acquired_at_level >= 1', name=op.f('ck_character_abilities_ck_character_abilities_acquired_at_level')),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], name=op.f('fk_character_abilities_ability_id_abilities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_abilities_character_id_characters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id', 'ability_id', 'id', name=op.f('pk_character_abilities'))
    )
    op.create_table('character_archetypes',
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('archetype_id', sa.Uuid(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('spell_casting_dc', sa.Integer(), nullable=True),
    sa.Column('spell_attack_bonus', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('level >= 1', name=op.f('ck_character_archetypes_ck_characters_archetypes_level')),
    sa.ForeignKeyConstraint(['archetype_id'], ['archetypes.id'], name='fk_characters_archetypes', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['archetype_id'], ['archetypes.id'], name=op.f('fk_character_archetypes_archetype_id_archetypes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_archetypes_character_id_characters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id', 'archetype_id', 'id', name=op.f('pk_character_archetypes'))
    )
    op.create_table('character_items',
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('equipped', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('attuned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_character_items_ck_character_items_quantity')),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_items_character_id_characters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_character_items_item_id_items'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('character_id', 'item_id', 'id', name=op.f('pk_character_items'))
    )
    op.create_table('character_skills',
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('proficient', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('expertise', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('bonus', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('not expertise or proficient', name=op.f('ck_character_skills_ck_character_skills_expertise_requires_proficiency')),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_skills_character_id_characters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_character_skills_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id', 'skill_id', 'id', name=op.f('pk_character_skills'))
    )
    op.create_table('character_spells',
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('spell_id', sa.Uuid(), nullable=False),
    sa.Column('archetype_id', sa.Uuid(), nullable=False),
    sa.Column('is_known', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_prepared', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('spell_slot_level', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('spell_slot_level is null or spell_slot_level between 0 and 9', name=op.f('ck_character_spells_ck_character_spells_slot_level')),
    sa.ForeignKeyConstraint(['archetype_id'], ['archetypes.id'], name=op.f('fk_character_spells_archetype_id_archetypes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_spells_character_id_characters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spell_id'], ['spells.id'], name=op.f('fk_character_spells_spell_id_spells'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id', 'spell_id', 'id', name=op.f('pk_character_spells'))
    )
    op.drop_table('inventories')
    op.add_column('characters', sa.Column('alignment', sa.Text(), nullable=True))
    op.add_column('characters', sa.Column('level', sa.Integer(), server_default='1', nullable=False))
    op.add_column('characters', sa.Column('experience', sa.Integer(), server_default='0', nullable=False))
    op.add_column('characters', sa.Column('proficiency_bonus', sa.Integer(), server_default='2', nullable=False))
    op.add_column('characters', sa.Column('armor_class', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('initiative', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('speed', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('max_hp', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('current_hp', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('temp_hp', sa.Integer(), server_default='0', nullable=False))
    op.add_column('characters', sa.Column('inspiration', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('characters', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'notes')
    op.drop_column('characters', 'inspiration')
    op.drop_column('characters', 'temp_hp')
    op.drop_column('characters', 'current_hp')
    op.drop_column('characters', 'max_hp')
    op.drop_column('characters', 'speed')
    op.drop_column('characters', 'initiative')
    op.drop_column('characters', 'armor_class')
    op.drop_column('characters', 'proficiency_bonus')
    op.drop_column('characters', 'experience')
    op.drop_column('characters', 'level')
    op.drop_column('characters', 'alignment')
    op.create_table('inventories',
    sa.Column('character_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('equipped', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('attuned', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_inventories_character_id_characters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_inventories_item_id_items'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('character_id', 'item_id', 'id', name=op.f('pk_inventories'))
    )
    op.drop_table('character_spells')
    op.drop_table('character_skills')
    op.drop_table('character_items')
    op.drop_table('character_archetypes')
    op.drop_table('character_abilities')
    op.drop_table('abilities')
    op.drop_table('spells')
    op.drop_table('skills')
    op.drop_table('archetypes')
    # ### end Alembic commands ###
