"""update user roles

Revision ID: 33d8a30c7231
Revises: 7650c4b9927e
Create Date: 2026-04-23 14:31:42.311592

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '33d8a30c7231'
down_revision: str | Sequence[str] | None = '7650c4b9927e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('description', sa.String(length=255), nullable=True))
    op.create_unique_constraint('uq_user_roles_user_id_role_id', 'user_roles', ['user_id', 'role_id'])
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_constraint('uq_user_roles_user_id_role_id', 'user_roles', type_='unique')
    op.drop_column('roles', 'description')
    # ### end Alembic commands ###
